### ISSUE TITLE
Suggestion: package as Nextcloud app

### ISSUE THREAD

**Issue by sunjam** [migueldemoura/myazo#10]
This would make a fantastic [Nextcloud app](https://docs.nextcloud.com/server/14/developer_manual/), which already uses php.  Together, these could make it possible to snap a screenshot and have a shared url in the clipboard.  I believe @splitt3r has been considering similar app ideas.

**Comment by migueldemoura** [comment]
I'd be open for integration. @splitt3r, can you shed some light on this?

**Comment by splitt3r** [comment]
I had a look at extending greenshot with a webdav upload feature. Do you mean that @sunjam? I will have a look at this later :+1:.
