### ISSUE TITLE
Adsense ads

### ISSUE THREAD

**Issue by ghusrcm** [migueldemoura/myazo#18]
Would it be possible that each destination url shows adsense ads?

**Comment by migueldemoura** [comment]
Hi @ghusrcm, I made the script to directly link to an image file, but you could change it to output HTML with the image embedded in it along with such ads.

The easiest way to do this without changing your webserver's configuration would be to:

- Create a php file called `display.php` with your HTML template and logic to accept a query parameter for the image to be displayed. Don't forget to validate the file name before using it.

- Replace https://github.com/migueldemoura/myazo/blob/master/server/src/upload.php#L45 with a link to `display.php` file and query parameter containing the file name.

I don't plan on adding this functionality to myazo, but I hope those pointers help addressing your use case!
