### ISSUE TITLE
macOS Script Error

### ISSUE THREAD

**Issue by NPCtom** [migueldemoura/myazo#19]
I get:
env: python3.8.5: Not a directory

When running the myazo.py script. Any idea on what I have done wrong?

**Comment by migueldemoura** [comment]
Hi @NPCtom, did you follow the installation instructions? How did you run the script?

I've just made some changes to simply installation (adding a global package install option alongside venvs), can you give it a go?

**Comment by migueldemoura** [comment]
Closing as `Timed out` since there's no updates for a month now, feel free to add more info here if the issue persists.
