### ISSUE TITLE
Desktop shortcut slow and taskbar shortcut not working at all

### ISSUE THREAD

**Issue by mtthidoteu** [migueldemoura/myazo#20]
Hello!
I have noticed something pretty strange. When executing the .pyw file it starts the program instantly, when executing it from a shortcut, there is a significant 4-10 seconds delay. And when executing the pinned shortcut from the Taskbar it doesn't execute at all (a small 'loading' icon appears, but that's all).
Any reason for this/Workarounds?
Thank you

**Comment by migueldemoura** [comment]
Hi there!

What version of Windows (output of `winver`) and myazo are you using? Did you install the python dependencies globally or using poetry?
Additionally, does the script work as expected when you execute it from PowerShell?

**Comment by migueldemoura** [comment]
Closing as timed out. Feel free to reopen if the issue still persists.
