### ISSUE TITLE
error on line 56 after take a screenshot

### ISSUE THREAD

**Issue by fferraro87** [migueldemoura/myazo#5]
Hi,
thanks for your work, but i've that problem after that i take a screenshot : 

```Traceback (most recent call last):
  File "/home/francesco/myazo-master/client/myazo.py", line 56, in <module>
    if config['Myazo'].get('clear_metadata'):
  File "/usr/lib64/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: ['Myazo']

```

I'm using the client on fedora os with python3 installed

**Comment by migueldemoura** [comment]
Should be fixed with https://github.com/migueldemoura/myazo/commit/8f5f75a8db28c96a60b4c49d0ad59b56058bf7b2. Let me know if the issue still persists :smiley:.
