### ISSUE TITLE
error with open URL

### ISSUE THREAD

**Issue by fferraro87** [migueldemoura/myazo#6]
Hi,
now i've that error when it try to open url : 

```
Gtk-Message: Failed to load module "unity-gtk-module"
   xdg-open - opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.



```

**Comment by migueldemoura** [comment]
By that message I'm assuming you have `xdg-open`. This may be an upstream issue of `webbrowser`. I'll check their source in a bit.

Can you try opening a terminal and entering: `xdg-open https://github.com`? What's the output?

**Comment by fferraro87** [comment]
with that command, he open that URL on firefox (my default browser web)

**Comment by migueldemoura** [comment]
Can you provide me with your fedora and xdg-open versions?

**Comment by fferraro87** [comment]
my fedora is 27 release and xdg-open 1.1.2+

**Comment by migueldemoura** [comment]
By the way, what's the python version?

**Comment by fferraro87** [comment]
Python 3.6.5

**Comment by migueldemoura** [comment]
Fairly sure this isn't a webbrowser issue. Can you add `print(url)` to L69 so we can check the var's contents (or debug it).

**Comment by fferraro87** [comment]
that's all output : 
```
[francesco@localhost ~]$ python3 /home/francesco/myazo-master/client/myazo.py 

(gnome-screenshot:7795): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2848:13: Expected a length

(gnome-screenshot:7795): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2880:37: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"

   xdg-open - opens a file or URL in the user's preferred
   application

Synopsis

   xdg-open { file | URL }

   xdg-open { --help | --manual | --version }

Use 'man xdg-open' or 'xdg-open --manual' for additional info.

(python3:7790): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2848:13: Expected a length

(python3:7790): Gtk-WARNING **: Theme parsing error: gtk-contained.css:2880:37: The :prelight pseudo-class is deprecated. Use :hover instead.
Gtk-Message: Failed to load module "unity-gtk-module"
Gtk-Message: Failed to load module "unity-gtk-module"
```

**Comment by fferraro87** [comment]
it seems that url isn't generated, if i print img var i've that output 
<_io.BufferedReader name='/tmp/w3a59aob.png'>

**Comment by migueldemoura** [comment]
Judging by your full output with the print(url), I'm guessing the server returns nothing (suppressed HTTP 500 message probably).
I'll add some error handling to make it easier to fix these issues. In the meantime, can you swap:

``` python
url = requests.post(
    ('{}?s={}').format(config['Myazo'].get('upload_script'), config['Myazo'].get('secret')),
    files={'screenshot': img}
).text
```

with 

``` python
response = requests.post(
    ('{}?s={}').format(config['Myazo'].get('upload_script'), config['Myazo'].get('secret')),
    files={'screenshot': img}
)
url = response.text
print('Got response "{}" with status "{}"'.format(url, response.status_code))
```
I'm guessing the status is 500.

**Comment by fferraro87** [comment]
yes the output status is 500

**Comment by fferraro87** [comment]
it's strange because i've that url : 
https://screenshot.levita.cloud/

and it works fine

**Comment by migueldemoura** [comment]
By that url I'm guessing you have access to the server. Can you check the Apache error log? It should be at `/var/log/httpd/error_log` for your distro.

Also, what value are you using `saveDirName`?

**Comment by fferraro87** [comment]
i've that error  on server side : 
`AH01071: Got error 'PHP message: PHP Fatal error: Call to undefined function random_bytes() in /var/www/vhosts/screenshot.levita.cloud/httpdocs/upload.php on line 31\n'`

on saveDirName i've `data/`

**Comment by migueldemoura** [comment]
That function is only available in PHP 7, you're probably on PHP 5.X. I'll issue a fix so it also works on version 5.X, as stated in the readme.

**Comment by fferraro87** [comment]
Ok thanks, i've switched to php 7 and now it works!
Thanks

**Comment by migueldemoura** [comment]
Glad I could help!
I'll keep this open until I push a change that makes it work on PHP 5 as well. I'm guessing most shared hosting is still on version 5.

**Comment by migueldemoura** [comment]
Fixed by https://github.com/migueldemoura/myazo/commit/f16df330f9e5ee247c4b20b787e3a77a28ce6cb8
